language: java

jdk:
  - oraclejdk8

services:
  - mysql

before-install:
  - mysql -u root -e "grant all privileges on *.* to 'root'@'localhost'"
  - mysql -u root -e "drop database if exist belajar"
  - mysql -u root -e "create database belajar"