language: java

jdk:
  - oraclejdk8

services:
  - mysql

before-script:
  - mysql -uroot -e "drop database if exist belajar;"
  - mysql -uroot -e "create database belajar;"
  - mysql -uroot -e "grant all privileges on *.* to 'root'@'localhost';"