language: java

jdk:
  - oraclejdk8

services:
  - mysql

before-install:
  - mysql -p "drop database if exist belajar"
  - mysql -p "create database belajar"
  - mysql -p "grant all privileges on belajar.* to 'root'@'localhost'"