language: java

jdk:
  - oraclejdk8

services:
  - mysql

before-script:
  - mysql -e "drop database if exist belajar"
  - mysql -e "create database belajar"
  - mysql -e "grant all privileges on belajar.* to 'root'@'localhost'"