language: java

jdk:
  - oraclejdk8

services:
  - mysql

before-install:
  - mysql -uroot -e "drop database if exist belajar"
  - mysql -uroot -e "create database belajar"
  - mysql -uroot -e "grant all privileges on belajar.* to 'root'@'localhost'"